resolve_script_dir <- function() {
  args_all <- commandArgs(trailingOnly = FALSE)
  file_arg <- args_all[grepl("^--file=", args_all)]

  if (length(file_arg) > 0) {
    return(dirname(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE)))
  }

  source_path <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)
  if (!is.null(source_path) && nzchar(source_path)) {
    return(dirname(normalizePath(source_path, winslash = "/", mustWork = FALSE)))
  }

  normalizePath(getwd(), winslash = "/", mustWork = FALSE)
}

script_dir <- resolve_script_dir()
project_dir <- normalizePath(file.path(script_dir, "..", ".."), winslash = "/", mustWork = TRUE)
endpoint_dir <- file.path(project_dir, "api", "endpoints")
output_file <- file.path(endpoint_dir, "_routes.generated.R")

endpoint_files <- c(
  "health.R",
  "swagger.R",
  "hevy.R",
  "workflows.R",
  "workflow-activity.R",
  "workflow-graph.R",
  "workflow-batch.R",
  "workflow-execution.R",
  "workflow-maintenance.R",
  "workflow-portability.R",
  "workflow-diff.R",
  "workflow-promotion.R",
  "notes.R",
  "tables.R",
  "admin.R"
)

missing_files <- endpoint_files[!file.exists(file.path(endpoint_dir, endpoint_files))]
if (length(missing_files) > 0) {
  stop(
    paste0(
      "Missing endpoint files: ",
      paste(missing_files, collapse = ", ")
    ),
    call. = FALSE
  )
}

output_lines <- c(
  "# Auto-generated by scripts/utils/build-routes.R. Do not edit manually.",
  "# Regenerate with: Rscript scripts/utils/build-routes.R",
  ""
)

for (i in seq_along(endpoint_files)) {
  endpoint_file <- endpoint_files[[i]]
  endpoint_path <- file.path(endpoint_dir, endpoint_file)
  output_lines <- c(
    output_lines,
    paste0("# ---- ", endpoint_file, " ----"),
    readLines(endpoint_path, warn = FALSE)
  )

  if (i < length(endpoint_files)) {
    output_lines <- c(output_lines, "")
  }
}

writeLines(output_lines, output_file, useBytes = TRUE)
cat("Generated routes file: ", normalizePath(output_file, winslash = "/", mustWork = FALSE), "\n", sep = "")
