# Auto-generated by scripts/utils/build-routes.R. Do not edit manually.
# Regenerate with: Rscript scripts/utils/build-routes.R

# ---- health.R ----
#* @apiTitle personal-api
#* @apiDescription API for notes and curated personal data warehouse metadata.
#* @apiTag System Endpoints for service availability and operational metadata.

#* Health check endpoint for uptime monitors and API clients
#* Returns service identity and current UTC time. No bearer token required.
#* @tag System
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Service is healthy and ready to receive requests.
#* @get /health
function() {
  list(
    status = "ok",
    service = "personal-api",
    timestamp_utc = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
  )
}

# ---- swagger.R ----
#* Redirect legacy Swagger endpoint to built-in docs UI.
#* Public endpoint. Redirect target: `/__docs__/`.
#* @tag System
#* @serializer text
#* @response 302 Redirect to the built-in Swagger UI endpoint.
#* @get /swagger/
function(res) {
  res$status <- 302
  res$setHeader("Location", "/__docs__/")
  "Redirecting to /__docs__/"
}

# ---- notes.R ----
#* List notes ordered by newest first.
#* Requires bearer authentication.
#* @tag Notes
#* @param limit:int Maximum records to return (clamped to 1..1000).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Notes returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @get /notes
function(limit = 100) {
  limit <- as.integer(limit)
  if (is.na(limit) || limit < 1) {
    limit <- 100
  }
  if (limit > 1000) {
    limit <- 1000
  }

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT id, text, created_at
      FROM notes
      ORDER BY created_at DESC
      LIMIT %d
      ",
      limit
    )
  )
}

#* Create a note from a JSON body.
#* Body shape: `{ \"text\": \"...\" }`.
#* Requires bearer authentication.
#* @tag Notes
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Note created successfully.
#* @response 400 Invalid JSON body or missing `text` field.
#* @response 401 Missing or invalid bearer token.
#* @post /notes
function(req, res) {
  body <- tryCatch(
    jsonlite::fromJSON(req$postBody %||% ""),
    error = function(e) NULL
  )

  if (is.null(body)) {
    res$status <- 400
    return(list(error = "Invalid JSON body"))
  }

  if (is.null(body$text) || length(body$text) != 1 || !is.character(body$text)) {
    res$status <- 400
    return(list(error = "Field 'text' is required"))
  }

  note_text <- trimws(body$text)
  if (!nzchar(note_text)) {
    res$status <- 400
    return(list(error = "Field 'text' is required"))
  }

  id <- uuid::UUIDgenerate()

  DBI::dbExecute(
    con,
    "INSERT INTO notes (id, text, created_at) VALUES (?, ?, CURRENT_TIMESTAMP)",
    params = list(id, note_text)
  )

  list(id = id, text = note_text, status = "created")
}

# ---- tables.R ----
#* List curated warehouse table metadata.
#* Requires bearer authentication.
#* @tag Warehouse
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Table metadata returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @get /tables
function() {
  DBI::dbGetQuery(
    con,
    "
    SELECT
      schema_name,
      table_name,
      object_name,
      source_path,
      relative_path,
      row_count,
      last_refresh
    FROM warehouse.tables
    ORDER BY schema_name, table_name
    "
  )
}

# ---- admin.R ----
#* Force a curated view refresh from Parquet mappings.
#* Requires bearer authentication.
#* @tag Warehouse
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Curated view refresh completed.
#* @response 401 Missing or invalid bearer token.
#* @post /admin/refresh-curated
function() {
  refresh_curated_views(force = TRUE)
}
