# Auto-generated by scripts/utils/build-routes.R. Do not edit manually.
# Regenerate with: Rscript scripts/utils/build-routes.R

# ---- health.R ----
#* @apiTitle personal-api
#* @apiDescription API for notes and curated personal data warehouse metadata.
#* @apiTag System Endpoints for service availability and operational metadata.

#* Health check endpoint for uptime monitors and API clients
#* Returns service identity and current UTC time. No bearer token required.
#* @tag System
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Service is healthy and ready to receive requests.
#* @get /health
function() {
  list(
    status = "ok",
    service = "personal-api",
    timestamp_utc = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
  )
}

# ---- swagger.R ----
#* Redirect legacy Swagger endpoint to built-in docs UI.
#* Public endpoint. Redirect target: `/__docs__/`.
#* @tag System
#* @serializer text
#* @response 302 Redirect to the built-in Swagger UI endpoint.
#* @get /swagger/
function(res) {
  res$status <- 302
  res$setHeader("Location", "/__docs__/")
  "Redirecting to /__docs__/"
}

# ---- hevy.R ----
#* Hevy API endpoints backed by curated DuckDB views.
#* Requires bearer authentication.

hevy_table_exists <- function(table) {
  DBI::dbExistsTable(con, DBI::Id(schema = "hevy", table = table))
}

missing_hevy_table <- function(res, table) {
  res$status <- 404
  list(error = paste0("Hevy table 'hevy.", table, "' is not available. Run Hevy sync first."))
}

read_hevy_state <- function(filename) {
  state_file <- file.path(personal_data_dir, "raw", "hevy", "_state", filename)
  if (!file.exists(state_file)) {
    return(NULL)
  }

  value <- trimws(readLines(state_file, warn = FALSE, n = 1))
  if (!nzchar(value)) {
    return(NULL)
  }

  value
}

read_hevy_last_refresh <- function() {
  has_warehouse_tables <- DBI::dbExistsTable(con, DBI::Id(schema = "warehouse", table = "tables"))
  if (!isTRUE(has_warehouse_tables)) {
    return(NULL)
  }

  out <- DBI::dbGetQuery(
    con,
    "
    SELECT MAX(last_refresh) AS last_refresh
    FROM warehouse.tables
    WHERE schema_name = 'hevy'
    "
  )

  value <- out$last_refresh[[1]]
  if (is.null(value) || is.na(value)) {
    return(NULL)
  }

  format(as.POSIXct(value, tz = "UTC"), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
}

hevy_table_status <- function(table) {
  exists <- isTRUE(hevy_table_exists(table))
  if (!exists) {
    return(list(exists = FALSE, row_count = NULL))
  }

  out <- DBI::dbGetQuery(
    con,
    sprintf('SELECT COUNT(*) AS n FROM "hevy"."%s"', table)
  )

  list(
    exists = TRUE,
    row_count = as.integer(out$n[[1]])
  )
}

clamp_int <- function(x, default, min_value, max_value) {
  out <- suppressWarnings(as.integer(x))
  if (is.na(out)) {
    out <- default
  }
  out <- max(out, min_value)
  min(out, max_value)
}

normalize_sort_field <- function(sort_by, allowed, default) {
  value <- trimws(as.character(sort_by %||% default))
  if (!nzchar(value) || !(value %in% allowed)) {
    return(default)
  }
  value
}

normalize_sort_order <- function(order, default = "desc") {
  value <- tolower(trimws(as.character(order %||% default)))
  if (!(value %in% c("asc", "desc"))) {
    return(default)
  }
  value
}

normalize_grain <- function(grain, default = "week") {
  value <- tolower(trimws(as.character(grain %||% default)))
  if (!(value %in% c("day", "week", "month"))) {
    return(default)
  }
  value
}

normalize_utc_time <- function(x) {
  if (is.null(x)) {
    return(NULL)
  }

  value <- trimws(as.character(x))
  if (!nzchar(value)) {
    return(NULL)
  }

  parsed <- suppressWarnings(as.POSIXct(value, tz = "UTC"))
  if (is.na(parsed)) {
    return(NULL)
  }

  parsed
}

#* Return Hevy sync and table availability status.
#* Requires bearer authentication.
#* @tag Hevy
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy status returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @get /hevy/status
function() {
  list(
    last_backfill_at = read_hevy_state("last_backfill_at.txt"),
    last_sync_at = read_hevy_state("last_sync_at.txt"),
    last_refresh_utc = read_hevy_last_refresh(),
    tables = list(
      workouts = hevy_table_status("workouts"),
      workout_exercises = hevy_table_status("workout_exercises"),
      sets = hevy_table_status("sets"),
      routines = hevy_table_status("routines")
    )
  )
}

#* Return Hevy aggregate summary metrics for a date window.
#* Requires bearer authentication.
#* @tag Hevy
#* @param from Only include workouts at or after this UTC timestamp (optional).
#* @param to Only include workouts at or before this UTC timestamp (optional).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy summary returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Required Hevy curated table is unavailable.
#* @get /hevy/summary
function(res, from = NULL, to = NULL) {
  if (!hevy_table_exists("workouts")) {
    return(missing_hevy_table(res, "workouts"))
  }
  if (!hevy_table_exists("sets")) {
    return(missing_hevy_table(res, "sets"))
  }

  from_time <- normalize_utc_time(from)
  to_time <- normalize_utc_time(to)

  where <- character()
  params <- list()

  if (!is.null(from_time)) {
    where <- c(where, "COALESCE(started_at, created_at) >= ?")
    params <- c(params, list(from_time))
  }
  if (!is.null(to_time)) {
    where <- c(where, "COALESCE(started_at, created_at) <= ?")
    params <- c(params, list(to_time))
  }

  where_sql <- if (length(where) == 0) "" else paste0("WHERE ", paste(where, collapse = " AND "))

  out <- DBI::dbGetQuery(
    con,
    sprintf(
      "
      WITH filtered_workouts AS (
        SELECT
          workout_id,
          CAST(COALESCE(started_at, created_at) AS TIMESTAMP) AS workout_time,
          duration_seconds
        FROM hevy.workouts
        %s
      ),
      workout_agg AS (
        SELECT
          COUNT(*) AS workouts,
          COUNT(DISTINCT CAST(workout_time AS DATE)) AS training_days,
          COALESCE(SUM(duration_seconds), 0) AS duration_seconds
        FROM filtered_workouts
      ),
      set_agg AS (
        SELECT
          COUNT(*) AS sets,
          COALESCE(SUM(COALESCE(s.reps, 0)), 0) AS reps,
          COALESCE(SUM(COALESCE(s.reps, 0) * COALESCE(s.weight_kg, 0)), 0) AS volume_kg
        FROM hevy.sets s
        INNER JOIN filtered_workouts w
          ON s.workout_id = w.workout_id
      )
      SELECT
        w.workouts,
        w.training_days,
        w.duration_seconds,
        s.sets,
        s.reps,
        s.volume_kg
      FROM workout_agg w
      CROSS JOIN set_agg s
      "
      ,
      where_sql
    ),
    params = params
  )

  list(
    from = if (is.null(from_time)) NULL else format(from_time, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"),
    to = if (is.null(to_time)) NULL else format(to_time, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"),
    workouts = as.integer(out$workouts[[1]]),
    training_days = as.integer(out$training_days[[1]]),
    duration_seconds = as.numeric(out$duration_seconds[[1]]),
    sets = as.integer(out$sets[[1]]),
    reps = as.numeric(out$reps[[1]]),
    volume_kg = as.numeric(out$volume_kg[[1]])
  )
}

#* Return Hevy aggregate metrics grouped by timeline period.
#* Requires bearer authentication.
#* @tag Hevy
#* @param grain Grouping granularity: `day`, `week`, or `month` (default `week`).
#* @param from Only include workouts at or after this UTC timestamp (optional).
#* @param to Only include workouts at or before this UTC timestamp (optional).
#* @param limit:int Maximum periods to return (clamped to 1..2000).
#* @param offset:int Periods to skip before returning results (clamped to 0..100000).
#* @param order Sort direction for period start: `asc` or `desc` (default `asc`).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy timeline returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Required Hevy curated table is unavailable.
#* @get /hevy/timeline
function(res, grain = "week", from = NULL, to = NULL, limit = 200, offset = 0, order = "asc") {
  if (!hevy_table_exists("workouts")) {
    return(missing_hevy_table(res, "workouts"))
  }
  if (!hevy_table_exists("sets")) {
    return(missing_hevy_table(res, "sets"))
  }

  grain <- normalize_grain(grain, default = "week")
  limit <- clamp_int(limit, default = 200L, min_value = 1L, max_value = 2000L)
  offset <- clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)
  order <- normalize_sort_order(order, default = "asc")
  from_time <- normalize_utc_time(from)
  to_time <- normalize_utc_time(to)

  where <- character()
  params <- list()

  if (!is.null(from_time)) {
    where <- c(where, "COALESCE(started_at, created_at) >= ?")
    params <- c(params, list(from_time))
  }
  if (!is.null(to_time)) {
    where <- c(where, "COALESCE(started_at, created_at) <= ?")
    params <- c(params, list(to_time))
  }

  where_sql <- if (length(where) == 0) "" else paste0("WHERE ", paste(where, collapse = " AND "))

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      WITH filtered_workouts AS (
        SELECT
          workout_id,
          CAST(COALESCE(started_at, created_at) AS TIMESTAMP) AS workout_time,
          COALESCE(duration_seconds, 0) AS duration_seconds
        FROM hevy.workouts
        %s
      ),
      set_by_workout AS (
        SELECT
          workout_id,
          COUNT(*) AS sets,
          COALESCE(SUM(COALESCE(reps, 0)), 0) AS reps,
          COALESCE(SUM(COALESCE(reps, 0) * COALESCE(weight_kg, 0)), 0) AS volume_kg
        FROM hevy.sets
        GROUP BY workout_id
      )
      SELECT
        DATE_TRUNC('%s', fw.workout_time) AS period_start,
        COUNT(*) AS workouts,
        COUNT(DISTINCT CAST(fw.workout_time AS DATE)) AS training_days,
        COALESCE(SUM(fw.duration_seconds), 0) AS duration_seconds,
        COALESCE(SUM(COALESCE(sw.sets, 0)), 0) AS sets,
        COALESCE(SUM(COALESCE(sw.reps, 0)), 0) AS reps,
        COALESCE(SUM(COALESCE(sw.volume_kg, 0)), 0) AS volume_kg
      FROM filtered_workouts fw
      LEFT JOIN set_by_workout sw
        ON sw.workout_id = fw.workout_id
      GROUP BY period_start
      ORDER BY period_start %s
      LIMIT %d
      OFFSET %d
      ",
      where_sql,
      grain,
      order,
      limit,
      offset
    ),
    params = params
  )
}

#* List Hevy exercises with aggregate usage metrics.
#* Requires bearer authentication.
#* @tag Hevy
#* @param limit:int Maximum records to return (clamped to 1..2000).
#* @param offset:int Records to skip before returning results (clamped to 0..100000).
#* @param search Optional case-insensitive exercise name search.
#* @param from Only include workouts at or after this UTC timestamp (optional).
#* @param to Only include workouts at or before this UTC timestamp (optional).
#* @param sort_by Sort field: one of `exercise_name`, `workouts`, `sets`, `reps`, `volume_kg`, `last_performed`.
#* @param order Sort direction: `asc` or `desc` (default `desc`).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy exercises returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Required Hevy curated table is unavailable.
#* @get /hevy/exercises
function(res, limit = 200, offset = 0, search = NULL, from = NULL, to = NULL, sort_by = "last_performed", order = "desc") {
  if (!hevy_table_exists("workouts")) {
    return(missing_hevy_table(res, "workouts"))
  }
  if (!hevy_table_exists("workout_exercises")) {
    return(missing_hevy_table(res, "workout_exercises"))
  }
  if (!hevy_table_exists("sets")) {
    return(missing_hevy_table(res, "sets"))
  }

  limit <- clamp_int(limit, default = 200L, min_value = 1L, max_value = 2000L)
  offset <- clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)
  sort_by <- normalize_sort_field(
    sort_by,
    allowed = c("exercise_name", "workouts", "sets", "reps", "volume_kg", "last_performed"),
    default = "last_performed"
  )
  order <- normalize_sort_order(order, default = "desc")
  from_time <- normalize_utc_time(from)
  to_time <- normalize_utc_time(to)
  search_value <- trimws(as.character(search %||% ""))
  has_search <- nzchar(search_value)

  where <- character()
  params <- list()

  if (!is.null(from_time)) {
    where <- c(where, "COALESCE(started_at, created_at) >= ?")
    params <- c(params, list(from_time))
  }
  if (!is.null(to_time)) {
    where <- c(where, "COALESCE(started_at, created_at) <= ?")
    params <- c(params, list(to_time))
  }

  where_sql <- if (length(where) == 0) "" else paste0("WHERE ", paste(where, collapse = " AND "))

  if (has_search) {
    params <- c(params, list(paste0("%", search_value, "%")))
  }

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      WITH filtered_workouts AS (
        SELECT
          workout_id,
          COALESCE(started_at, created_at) AS workout_time
        FROM hevy.workouts
        %s
      ),
      exercise_sets AS (
        SELECT
          we.exercise_id,
          COALESCE(NULLIF(TRIM(we.exercise_name), ''), we.exercise_id) AS exercise_name,
          we.workout_id,
          fw.workout_time,
          s.set_index,
          COALESCE(s.reps, 0) AS reps,
          COALESCE(s.weight_kg, 0) AS weight_kg
        FROM hevy.workout_exercises we
        INNER JOIN filtered_workouts fw
          ON we.workout_id = fw.workout_id
        LEFT JOIN hevy.sets s
          ON s.workout_id = we.workout_id
         AND s.exercise_index = we.exercise_index
        WHERE we.exercise_id IS NOT NULL
          AND TRIM(we.exercise_id) <> ''
      )
      SELECT
        exercise_id,
        exercise_name,
        COUNT(DISTINCT workout_id) AS workouts,
        COUNT(set_index) AS sets,
        COALESCE(SUM(reps), 0) AS reps,
        COALESCE(SUM(reps * weight_kg), 0) AS volume_kg,
        MAX(workout_time) AS last_performed
      FROM exercise_sets
      %s
      GROUP BY exercise_id, exercise_name
      ORDER BY %s %s, exercise_id ASC
      LIMIT %d
      OFFSET %d
      ",
      where_sql,
      if (has_search) "WHERE LOWER(exercise_name) LIKE LOWER(?)" else "",
      sort_by,
      order,
      limit,
      offset
    ),
    params = params
  )
}

#* Return per-workout history for a single Hevy exercise.
#* Requires bearer authentication.
#* @tag Hevy
#* @param exercise_id Exercise id from Hevy.
#* @param limit:int Maximum records to return (clamped to 1..2000).
#* @param offset:int Records to skip before returning results (clamped to 0..100000).
#* @param from Only include workouts at or after this UTC timestamp (optional).
#* @param to Only include workouts at or before this UTC timestamp (optional).
#* @param order Sort direction for workout time: `asc` or `desc` (default `desc`).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy exercise history returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Exercise not found or required Hevy curated table is unavailable.
#* @get /hevy/exercises/<exercise_id>/history
function(res, exercise_id, limit = 200, offset = 0, from = NULL, to = NULL, order = "desc") {
  if (!hevy_table_exists("workouts")) {
    return(missing_hevy_table(res, "workouts"))
  }
  if (!hevy_table_exists("workout_exercises")) {
    return(missing_hevy_table(res, "workout_exercises"))
  }
  if (!hevy_table_exists("sets")) {
    return(missing_hevy_table(res, "sets"))
  }

  exercise_id <- trimws(as.character(exercise_id %||% ""))
  if (!nzchar(exercise_id)) {
    res$status <- 404
    return(list(error = "Exercise not found"))
  }

  exists <- DBI::dbGetQuery(
    con,
    "
    SELECT 1 AS found
    FROM hevy.workout_exercises
    WHERE exercise_id = ?
    LIMIT 1
    ",
    params = list(exercise_id)
  )

  if (nrow(exists) == 0) {
    res$status <- 404
    return(list(error = "Exercise not found"))
  }

  limit <- clamp_int(limit, default = 200L, min_value = 1L, max_value = 2000L)
  offset <- clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)
  order <- normalize_sort_order(order, default = "desc")
  from_time <- normalize_utc_time(from)
  to_time <- normalize_utc_time(to)

  where <- c("we.exercise_id = ?")
  params <- list(exercise_id)

  if (!is.null(from_time)) {
    where <- c(where, "COALESCE(w.started_at, w.created_at) >= ?")
    params <- c(params, list(from_time))
  }
  if (!is.null(to_time)) {
    where <- c(where, "COALESCE(w.started_at, w.created_at) <= ?")
    params <- c(params, list(to_time))
  }

  where_sql <- paste(where, collapse = " AND ")

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT
        we.exercise_id,
        COALESCE(NULLIF(TRIM(we.exercise_name), ''), we.exercise_id) AS exercise_name,
        w.workout_id,
        w.title AS workout_title,
        COALESCE(w.started_at, w.created_at) AS workout_time,
        COUNT(s.set_index) AS sets,
        COALESCE(SUM(COALESCE(s.reps, 0)), 0) AS reps,
        COALESCE(MAX(COALESCE(s.weight_kg, 0)), 0) AS top_weight_kg,
        COALESCE(SUM(COALESCE(s.reps, 0) * COALESCE(s.weight_kg, 0)), 0) AS volume_kg
      FROM hevy.workout_exercises we
      INNER JOIN hevy.workouts w
        ON we.workout_id = w.workout_id
      LEFT JOIN hevy.sets s
        ON s.workout_id = we.workout_id
       AND s.exercise_index = we.exercise_index
      WHERE %s
      GROUP BY
        we.exercise_id,
        COALESCE(NULLIF(TRIM(we.exercise_name), ''), we.exercise_id),
        w.workout_id,
        w.title,
        COALESCE(w.started_at, w.created_at)
      ORDER BY workout_time %s, w.workout_id ASC
      LIMIT %d
      OFFSET %d
      ",
      where_sql,
      order,
      limit,
      offset
    ),
    params = params
  )
}

#* List Hevy workouts ordered by most recent start time.
#* Requires bearer authentication.
#* @tag Hevy
#* @param limit:int Maximum records to return (clamped to 1..1000).
#* @param offset:int Records to skip before returning results (clamped to 0..100000).
#* @param from Only include workouts at or after this UTC timestamp (optional).
#* @param to Only include workouts at or before this UTC timestamp (optional).
#* @param sort_by Sort field: one of `started_at`, `created_at`, `updated_at`, `duration_seconds`, `title`.
#* @param order Sort direction: `asc` or `desc` (default `desc`).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy workouts returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Hevy curated workouts table is unavailable.
#* @get /hevy/workouts
function(res, limit = 100, offset = 0, from = NULL, to = NULL, sort_by = "started_at", order = "desc") {
  if (!hevy_table_exists("workouts")) {
    return(missing_hevy_table(res, "workouts"))
  }

  limit <- clamp_int(limit, default = 100L, min_value = 1L, max_value = 1000L)
  offset <- clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)
  sort_by <- normalize_sort_field(
    sort_by,
    allowed = c("started_at", "created_at", "updated_at", "duration_seconds", "title"),
    default = "started_at"
  )
  order <- normalize_sort_order(order, default = "desc")
  from_time <- normalize_utc_time(from)
  to_time <- normalize_utc_time(to)

  where <- character()
  params <- list()

  if (!is.null(from_time)) {
    where <- c(where, "COALESCE(started_at, created_at) >= ?")
    params <- c(params, list(from_time))
  }
  if (!is.null(to_time)) {
    where <- c(where, "COALESCE(started_at, created_at) <= ?")
    params <- c(params, list(to_time))
  }

  where_sql <- if (length(where) == 0) "" else paste0("WHERE ", paste(where, collapse = " AND "))

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT
        workout_id,
        title,
        description,
        started_at,
        ended_at,
        duration_seconds,
        created_at,
        updated_at
      FROM hevy.workouts
      %s
      ORDER BY %s %s
      LIMIT %d
      OFFSET %d
      ",
      where_sql,
      sort_by,
      order,
      limit
      ,
      offset
    ),
    params = params
  )
}

#* Get one Hevy workout by id.
#* Requires bearer authentication.
#* @tag Hevy
#* @param workout_id Workout id from Hevy.
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy workout returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Workout not found or Hevy workouts table unavailable.
#* @get /hevy/workouts/<workout_id>
function(res, workout_id) {
  if (!hevy_table_exists("workouts")) {
    return(missing_hevy_table(res, "workouts"))
  }

  out <- DBI::dbGetQuery(
    con,
    "
    SELECT
      workout_id,
      title,
      description,
      started_at,
      ended_at,
      duration_seconds,
      created_at,
      updated_at
    FROM hevy.workouts
    WHERE workout_id = ?
    LIMIT 1
    ",
    params = list(workout_id)
  )

  if (nrow(out) == 0) {
    res$status <- 404
    return(list(error = "Workout not found"))
  }

  out
}

#* Get one Hevy workout with related exercises and sets.
#* Requires bearer authentication.
#* @tag Hevy
#* @param workout_id Workout id from Hevy.
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Full Hevy workout payload returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Workout not found or Hevy workouts table unavailable.
#* @get /hevy/workouts/<workout_id>/full
function(res, workout_id) {
  if (!hevy_table_exists("workouts")) {
    return(missing_hevy_table(res, "workouts"))
  }

  workout <- DBI::dbGetQuery(
    con,
    "
    SELECT
      workout_id,
      title,
      description,
      started_at,
      ended_at,
      duration_seconds,
      created_at,
      updated_at
    FROM hevy.workouts
    WHERE workout_id = ?
    LIMIT 1
    ",
    params = list(workout_id)
  )

  if (nrow(workout) == 0) {
    res$status <- 404
    return(list(error = "Workout not found"))
  }

  exercises <- if (hevy_table_exists("workout_exercises")) {
    DBI::dbGetQuery(
      con,
      "
      SELECT
        workout_id,
        exercise_index,
        exercise_id,
        exercise_name,
        notes
      FROM hevy.workout_exercises
      WHERE workout_id = ?
      ORDER BY exercise_index
      ",
      params = list(workout_id)
    )
  } else {
    data.frame(
      workout_id = character(),
      exercise_index = integer(),
      exercise_id = character(),
      exercise_name = character(),
      notes = character(),
      stringsAsFactors = FALSE
    )
  }

  sets <- if (hevy_table_exists("sets")) {
    DBI::dbGetQuery(
      con,
      "
      SELECT
        workout_id,
        exercise_index,
        set_index,
        set_type,
        reps,
        weight_kg,
        distance_m,
        duration_seconds,
        rpe,
        is_warmup,
        notes
      FROM hevy.sets
      WHERE workout_id = ?
      ORDER BY exercise_index, set_index
      ",
      params = list(workout_id)
    )
  } else {
    data.frame(
      workout_id = character(),
      exercise_index = integer(),
      set_index = integer(),
      set_type = character(),
      reps = numeric(),
      weight_kg = numeric(),
      distance_m = numeric(),
      duration_seconds = numeric(),
      rpe = numeric(),
      is_warmup = logical(),
      notes = character(),
      stringsAsFactors = FALSE
    )
  }

  list(
    workout = workout[1, , drop = FALSE],
    exercises = exercises,
    sets = sets
  )
}

#* List Hevy workout exercises.
#* Requires bearer authentication.
#* @tag Hevy
#* @param workout_id Filter to one workout id (optional).
#* @param limit:int Maximum records to return (clamped to 1..5000).
#* @param offset:int Records to skip before returning results (clamped to 0..100000).
#* @param sort_by Sort field: one of `workout_id`, `exercise_index`, `exercise_name`.
#* @param order Sort direction: `asc` or `desc` (default `asc`).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy workout exercises returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Hevy curated workout_exercises table is unavailable.
#* @get /hevy/workout-exercises
function(res, workout_id = NULL, limit = 500, offset = 0, sort_by = "workout_id", order = "asc") {
  if (!hevy_table_exists("workout_exercises")) {
    return(missing_hevy_table(res, "workout_exercises"))
  }

  limit <- clamp_int(limit, default = 500L, min_value = 1L, max_value = 5000L)
  offset <- clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)
  sort_by <- normalize_sort_field(
    sort_by,
    allowed = c("workout_id", "exercise_index", "exercise_name"),
    default = "workout_id"
  )
  order <- normalize_sort_order(order, default = "asc")

  if (!is.null(workout_id) && nzchar(trimws(workout_id))) {
    return(
      DBI::dbGetQuery(
        con,
        sprintf(
          "
          SELECT
            workout_id,
            exercise_index,
            exercise_id,
            exercise_name,
            notes
          FROM hevy.workout_exercises
          WHERE workout_id = ?
          ORDER BY %s %s, exercise_index ASC
          LIMIT %d
          OFFSET %d
          ",
          sort_by,
          order,
          limit
          ,
          offset
        ),
        params = list(trimws(workout_id))
      )
    )
  }

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT
        workout_id,
        exercise_index,
        exercise_id,
        exercise_name,
        notes
      FROM hevy.workout_exercises
      ORDER BY %s %s, workout_id ASC, exercise_index ASC
      LIMIT %d
      OFFSET %d
      ",
      sort_by,
      order,
      limit
      ,
      offset
    )
  )
}

#* List Hevy sets.
#* Requires bearer authentication.
#* @tag Hevy
#* @param workout_id Filter to one workout id (optional).
#* @param limit:int Maximum records to return (clamped to 1..10000).
#* @param offset:int Records to skip before returning results (clamped to 0..100000).
#* @param sort_by Sort field: one of `workout_id`, `exercise_index`, `set_index`, `reps`, `weight_kg`.
#* @param order Sort direction: `asc` or `desc` (default `asc`).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy sets returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Hevy curated sets table is unavailable.
#* @get /hevy/sets
function(res, workout_id = NULL, limit = 1000, offset = 0, sort_by = "workout_id", order = "asc") {
  if (!hevy_table_exists("sets")) {
    return(missing_hevy_table(res, "sets"))
  }

  limit <- clamp_int(limit, default = 1000L, min_value = 1L, max_value = 10000L)
  offset <- clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)
  sort_by <- normalize_sort_field(
    sort_by,
    allowed = c("workout_id", "exercise_index", "set_index", "reps", "weight_kg"),
    default = "workout_id"
  )
  order <- normalize_sort_order(order, default = "asc")

  if (!is.null(workout_id) && nzchar(trimws(workout_id))) {
    return(
      DBI::dbGetQuery(
        con,
        sprintf(
          "
          SELECT
            workout_id,
            exercise_index,
            set_index,
            set_type,
            reps,
            weight_kg,
            distance_m,
            duration_seconds,
            rpe,
            is_warmup,
            notes
          FROM hevy.sets
          WHERE workout_id = ?
          ORDER BY %s %s, exercise_index ASC, set_index ASC
          LIMIT %d
          OFFSET %d
          ",
          sort_by,
          order,
          limit
          ,
          offset
        ),
        params = list(trimws(workout_id))
      )
    )
  }

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT
        workout_id,
        exercise_index,
        set_index,
        set_type,
        reps,
        weight_kg,
        distance_m,
        duration_seconds,
        rpe,
        is_warmup,
        notes
      FROM hevy.sets
      ORDER BY %s %s, workout_id ASC, exercise_index ASC, set_index ASC
      LIMIT %d
      OFFSET %d
      ",
      sort_by,
      order,
      limit
      ,
      offset
    )
  )
}

#* List Hevy routines.
#* Requires bearer authentication.
#* @tag Hevy
#* @param limit:int Maximum records to return (clamped to 1..2000).
#* @param offset:int Records to skip before returning results (clamped to 0..100000).
#* @param sort_by Sort field: one of `updated_at`, `routine_name`, `routine_id`.
#* @param order Sort direction: `asc` or `desc` (default `desc`).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Hevy routines returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @response 404 Hevy curated routines table is unavailable.
#* @get /hevy/routines
function(res, limit = 500, offset = 0, sort_by = "updated_at", order = "desc") {
  if (!hevy_table_exists("routines")) {
    return(missing_hevy_table(res, "routines"))
  }

  limit <- clamp_int(limit, default = 500L, min_value = 1L, max_value = 2000L)
  offset <- clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)
  sort_by <- normalize_sort_field(
    sort_by,
    allowed = c("updated_at", "routine_name", "routine_id"),
    default = "updated_at"
  )
  order <- normalize_sort_order(order, default = "desc")

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT
        routine_id,
        folder_id,
        routine_name,
        updated_at
      FROM hevy.routines
      ORDER BY %s %s, routine_id ASC
      LIMIT %d
      OFFSET %d
      ",
      sort_by,
      order,
      limit
      ,
      offset
    )
  )
}

# ---- workflows.R ----
#* Workflow storage endpoints for contexts, skills, and automations.
#* Requires bearer authentication.

wf_object_specs <- list(
  context = list(table = "contexts", id_col = "context_id"),
  skill = list(table = "skills", id_col = "skill_id"),
  automation = list(table = "automations", id_col = "automation_id")
)

wf_required_tables <- c("contexts", "skills", "automations", "versions", "tags", "dependencies")

wf_scope <- function(workspace = "personal", project = "default", env = "dev") {
  clean <- function(x, default) {
    value <- trimws(as.character(x %||% default))
    if (!nzchar(value)) {
      return(default)
    }
    value
  }

  list(
    workspace = clean(workspace, "personal"),
    project = clean(project, "default"),
    env = clean(env, "dev")
  )
}

wf_clamp_int <- function(x, default, min_value, max_value) {
  out <- suppressWarnings(as.integer(x))
  if (is.na(out)) {
    out <- default
  }
  out <- max(out, min_value)
  min(out, max_value)
}

wf_sort_order <- function(order, default = "desc") {
  value <- tolower(trimws(as.character(order %||% default)))
  if (!(value %in% c("asc", "desc"))) {
    return(default)
  }
  value
}

wf_sort_field <- function(sort_by, allowed, default) {
  value <- trimws(as.character(sort_by %||% default))
  if (!nzchar(value) || !(value %in% allowed)) {
    return(default)
  }
  value
}

wf_object_type <- function(object_type) {
  out <- tolower(trimws(as.character(object_type %||% "")))
  if (!(out %in% names(wf_object_specs))) {
    return(NULL)
  }
  out
}

wf_id <- function(id) {
  value <- trimws(as.character(id %||% ""))
  if (!nzchar(value)) {
    return(NULL)
  }
  value
}

wf_json_parse <- function(req, res) {
  parsed <- tryCatch(
    jsonlite::fromJSON(req$postBody %||% "", simplifyVector = FALSE),
    error = function(e) NULL
  )

  if (is.null(parsed) || !is.list(parsed)) {
    res$status <- 400
    return(list(error = "Invalid JSON body"))
  }

  parsed
}

wf_json_encode <- function(value) {
  jsonlite::toJSON(value, auto_unbox = TRUE, null = "null")
}

wf_json_decode <- function(value) {
  if (is.null(value) || is.na(value) || !nzchar(value)) {
    return(NULL)
  }

  tryCatch(
    jsonlite::fromJSON(value, simplifyVector = FALSE),
    error = function(e) value
  )
}

wf_missing_table <- function(res, table_name) {
  res$status <- 503
  list(error = paste0("Missing required table '", table_name, "'. Run scripts/0000-init-duckdb.R."))
}

wf_ensure_tables <- function(res) {
  for (tbl in wf_required_tables) {
    if (!isTRUE(DBI::dbExistsTable(con, tbl))) {
      return(wf_missing_table(res, tbl))
    }
  }

  NULL
}

wf_find_object <- function(object_type, object_id, scope) {
  spec <- wf_object_specs[[object_type]]
  if (is.null(spec)) {
    return(NULL)
  }

  sql <- sprintf(
    "
    SELECT *
    FROM %s
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND %s = ?
    LIMIT 1
    ",
    spec$table,
    spec$id_col
  )

  out <- DBI::dbGetQuery(
    con,
    sql,
    params = list(scope$workspace, scope$project, scope$env, object_id)
  )

  if (nrow(out) == 0) {
    return(NULL)
  }

  out[1, , drop = FALSE]
}

wf_get_tags <- function(object_type, object_id, scope) {
  out <- DBI::dbGetQuery(
    con,
    "
    SELECT tag
    FROM tags
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND object_type = ?
      AND object_id = ?
    ORDER BY tag
    ",
    params = list(scope$workspace, scope$project, scope$env, object_type, object_id)
  )

  as.character(out$tag %||% character())
}

wf_get_dependencies <- function(source_type, source_id, scope) {
  DBI::dbGetQuery(
    con,
    "
    SELECT source_type, source_id, target_type, target_id, required, created_at
    FROM dependencies
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND source_type = ?
      AND source_id = ?
    ORDER BY target_type, target_id
    ",
    params = list(scope$workspace, scope$project, scope$env, source_type, source_id)
  )
}

wf_next_version <- function(object_type, object_id, scope) {
  out <- DBI::dbGetQuery(
    con,
    "
    SELECT COALESCE(MAX(version), 0) + 1 AS next_version
    FROM versions
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND object_type = ?
      AND object_id = ?
    ",
    params = list(scope$workspace, scope$project, scope$env, object_type, object_id)
  )

  as.integer(out$next_version[[1]])
}

wf_object_to_response <- function(object_type, row, scope, version = NULL) {
  spec <- wf_object_specs[[object_type]]
  id_col <- spec$id_col
  object_id <- as.character(row[[id_col]][[1]])
  tags <- wf_get_tags(object_type, object_id, scope)
  dependencies <- NULL

  if (identical(object_type, "automation")) {
    dependencies <- wf_get_dependencies("automation", object_id, scope)
  }

  out <- list(
    object_type = object_type,
    object_id = object_id,
    workspace = as.character(row$workspace[[1]]),
    project = as.character(row$project[[1]]),
    env = as.character(row$env[[1]]),
    title = as.character(row$title[[1]] %||% ""),
    content = wf_json_decode(row$content_json[[1]]),
    tags = tags,
    dependencies = dependencies,
    updated_at = as.character(row$updated_at[[1]]),
    updated_by = as.character(row$updated_by[[1]] %||% ""),
    published_version = as.integer(row$published_version[[1]] %||% 0L),
    version = version
  )

  if (identical(object_type, "automation")) {
    out$trigger_type <- as.character(row$trigger_type[[1]] %||% "")
    out$enabled <- isTRUE(row$enabled[[1]] %||% FALSE)
  }

  out
}

wf_version_to_response <- function(row) {
  list(
    object_type = as.character(row$object_type[[1]]),
    object_id = as.character(row$object_id[[1]]),
    workspace = as.character(row$workspace[[1]]),
    project = as.character(row$project[[1]]),
    env = as.character(row$env[[1]]),
    version = as.integer(row$version[[1]]),
    title = as.character(row$title[[1]] %||% ""),
    content = wf_json_decode(row$content_json[[1]]),
    tags = wf_json_decode(row$tags_json[[1]]),
    dependencies = wf_json_decode(row$dependencies_json[[1]]),
    source_updated_at = as.character(row$source_updated_at[[1]]),
    created_at = as.character(row$created_at[[1]]),
    created_by = as.character(row$created_by[[1]] %||% ""),
    change_note = as.character(row$change_note[[1]] %||% "")
  )
}

wf_list_objects <- function(object_type, scope, tag = NULL, q = NULL, sort_by = "updated_at", order = "desc", limit = 100, offset = 0) {
  spec <- wf_object_specs[[object_type]]
  sort_by <- wf_sort_field(sort_by, allowed = c(spec$id_col, "title", "updated_at", "published_version"), default = "updated_at")
  order <- wf_sort_order(order, default = "desc")
  limit <- wf_clamp_int(limit, default = 100L, min_value = 1L, max_value = 1000L)
  offset <- wf_clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)

  q <- trimws(as.character(q %||% ""))
  tag <- trimws(as.character(tag %||% ""))
  has_q <- nzchar(q)
  has_tag <- nzchar(tag)

  where <- c("workspace = ?", "project = ?", "env = ?")
  params <- list(scope$workspace, scope$project, scope$env)

  if (has_q) {
    where <- c(where, sprintf("(LOWER(%s) LIKE LOWER(?) OR LOWER(COALESCE(title, '')) LIKE LOWER(?))", spec$id_col))
    params <- c(params, list(paste0("%", q, "%"), paste0("%", q, "%")))
  }

  if (has_tag) {
    where <- c(where, sprintf("EXISTS (SELECT 1 FROM tags t WHERE t.workspace = %s.workspace AND t.project = %s.project AND t.env = %s.env AND t.object_type = ? AND t.object_id = %s.%s AND t.tag = ?)", spec$table, spec$table, spec$table, spec$table, spec$id_col))
    params <- c(params, list(object_type, tag))
  }

  where_sql <- paste(where, collapse = " AND ")

  total <- DBI::dbGetQuery(
    con,
    sprintf("SELECT COUNT(*) AS n FROM %s WHERE %s", spec$table, where_sql),
    params = params
  )

  rows <- DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT *
      FROM %s
      WHERE %s
      ORDER BY %s %s
      LIMIT %d
      OFFSET %d
      ",
      spec$table,
      where_sql,
      sort_by,
      order,
      limit,
      offset
    ),
    params = params
  )

  items <- lapply(
    seq_len(nrow(rows)),
    function(i) wf_object_to_response(object_type, rows[i, , drop = FALSE], scope = scope)
  )

  list(
    items = items,
    total = as.integer(total$n[[1]]),
    limit = limit,
    offset = offset
  )
}

wf_upsert_object <- function(res, req, object_type, object_id, scope) {
  parsed <- wf_json_parse(req, res)
  if (!is.list(parsed) || !is.null(parsed$error)) {
    return(parsed)
  }

  id <- wf_id(object_id)
  if (is.null(id)) {
    res$status <- 400
    return(list(error = "Object id is required"))
  }

  title <- trimws(as.character(parsed$title %||% ""))
  content <- parsed$content %||% parsed$body %||% list()
  updated_by <- trimws(as.character(parsed$updated_by %||% ""))

  spec <- wf_object_specs[[object_type]]
  existing <- wf_find_object(object_type, id, scope)
  content_json <- wf_json_encode(content)

  if (is.null(existing)) {
    DBI::dbExecute(
      con,
      sprintf(
        "
        INSERT INTO %s (workspace, project, env, %s, title, content_json, updated_at, updated_by, published_version%s)
        VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, 0%s)
        ",
        spec$table,
        spec$id_col,
        if (identical(object_type, "automation")) ", trigger_type, enabled" else "",
        if (identical(object_type, "automation")) ", ?, ?" else ""
      ),
      params = c(
        list(scope$workspace, scope$project, scope$env, id, title, content_json, updated_by),
        if (identical(object_type, "automation")) {
          list(trimws(as.character(parsed$trigger_type %||% "")), isTRUE(parsed$enabled %||% TRUE))
        } else {
          list()
        }
      )
    )
  } else {
    DBI::dbExecute(
      con,
      sprintf(
        "
        UPDATE %s
        SET title = ?,
            content_json = ?,
            updated_at = CURRENT_TIMESTAMP,
            updated_by = ?
            %s
        WHERE workspace = ?
          AND project = ?
          AND env = ?
          AND %s = ?
        ",
        spec$table,
        if (identical(object_type, "automation")) ", trigger_type = ?, enabled = ?" else "",
        spec$id_col
      ),
      params = c(
        list(title, content_json, updated_by),
        if (identical(object_type, "automation")) {
          list(trimws(as.character(parsed$trigger_type %||% "")), isTRUE(parsed$enabled %||% TRUE))
        } else {
          list()
        },
        list(scope$workspace, scope$project, scope$env, id)
      )
    )
  }

  row <- wf_find_object(object_type, id, scope)
  list(status = "saved", object = wf_object_to_response(object_type, row, scope = scope))
}

wf_get_object <- function(res, object_type, object_id, scope, version = NULL) {
  id <- wf_id(object_id)
  if (is.null(id)) {
    res$status <- 400
    return(list(error = "Object id is required"))
  }

  version_txt <- trimws(as.character(version %||% ""))
  if (!nzchar(version_txt)) {
    row <- wf_find_object(object_type, id, scope)
    if (is.null(row)) {
      res$status <- 404
      return(list(error = "Object not found"))
    }
    return(wf_object_to_response(object_type, row, scope = scope))
  }

  if (identical(tolower(version_txt), "latest")) {
    current <- wf_find_object(object_type, id, scope)
    if (is.null(current)) {
      res$status <- 404
      return(list(error = "Object not found"))
    }

    latest_version <- as.integer(current$published_version[[1]] %||% 0L)
    if (latest_version <= 0L) {
      return(wf_object_to_response(object_type, current, scope = scope))
    }

    version_txt <- as.character(latest_version)
  }

  version_no <- suppressWarnings(as.integer(version_txt))
  if (is.na(version_no) || version_no < 1L) {
    res$status <- 400
    return(list(error = "Version must be a positive integer or 'latest'"))
  }

  row <- DBI::dbGetQuery(
    con,
    "
    SELECT *
    FROM versions
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND object_type = ?
      AND object_id = ?
      AND version = ?
    LIMIT 1
    ",
    params = list(scope$workspace, scope$project, scope$env, object_type, id, version_no)
  )

  if (nrow(row) == 0) {
    res$status <- 404
    return(list(error = "Version not found"))
  }

  wf_version_to_response(row[1, , drop = FALSE])
}

wf_publish_object <- function(res, req, object_type, object_id, scope) {
  id <- wf_id(object_id)
  if (is.null(id)) {
    res$status <- 400
    return(list(error = "Object id is required"))
  }

  current <- wf_find_object(object_type, id, scope)
  if (is.null(current)) {
    res$status <- 404
    return(list(error = "Object not found"))
  }

  parsed <- wf_json_parse(req, res)
  if (!is.list(parsed) || !is.null(parsed$error)) {
    return(parsed)
  }

  created_by <- trimws(as.character(parsed$updated_by %||% parsed$created_by %||% ""))
  change_note <- trimws(as.character(parsed$change_note %||% ""))

  version_no <- wf_next_version(object_type, id, scope)
  tags <- wf_get_tags(object_type, id, scope)
  dependencies <- if (identical(object_type, "automation")) {
    wf_get_dependencies("automation", id, scope)
  } else {
    NULL
  }

  spec <- wf_object_specs[[object_type]]

  DBI::dbExecute(
    con,
    "
    INSERT INTO versions (
      workspace, project, env, object_type, object_id, version, title,
      content_json, tags_json, dependencies_json, source_updated_at,
      created_at, created_by, change_note
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, ?)
    ",
    params = list(
      scope$workspace,
      scope$project,
      scope$env,
      object_type,
      id,
      version_no,
      as.character(current$title[[1]] %||% ""),
      as.character(current$content_json[[1]]),
      wf_json_encode(tags),
      wf_json_encode(dependencies),
      as.character(current$updated_at[[1]]),
      created_by,
      change_note
    )
  )

  DBI::dbExecute(
    con,
    sprintf(
      "
      UPDATE %s
      SET published_version = ?,
          updated_at = CURRENT_TIMESTAMP
      WHERE workspace = ?
        AND project = ?
        AND env = ?
        AND %s = ?
      ",
      spec$table,
      spec$id_col
    ),
    params = list(version_no, scope$workspace, scope$project, scope$env, id)
  )

  list(status = "published", version = version_no)
}

wf_list_versions <- function(object_type, object_id, scope) {
  id <- wf_id(object_id)
  if (is.null(id)) {
    return(data.frame())
  }

  DBI::dbGetQuery(
    con,
    "
    SELECT
      object_type,
      object_id,
      version,
      title,
      source_updated_at,
      created_at,
      created_by,
      change_note
    FROM versions
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND object_type = ?
      AND object_id = ?
    ORDER BY version DESC
    ",
    params = list(scope$workspace, scope$project, scope$env, object_type, id)
  )
}

wf_rollback <- function(res, req, object_type, object_id, scope) {
  id <- wf_id(object_id)
  if (is.null(id)) {
    res$status <- 400
    return(list(error = "Object id is required"))
  }

  parsed <- wf_json_parse(req, res)
  if (!is.list(parsed) || !is.null(parsed$error)) {
    return(parsed)
  }

  version_no <- suppressWarnings(as.integer(parsed$version %||% NA_integer_))
  if (is.na(version_no) || version_no < 1L) {
    res$status <- 400
    return(list(error = "Field 'version' must be a positive integer"))
  }

  version_row <- DBI::dbGetQuery(
    con,
    "
    SELECT *
    FROM versions
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND object_type = ?
      AND object_id = ?
      AND version = ?
    LIMIT 1
    ",
    params = list(scope$workspace, scope$project, scope$env, object_type, id, version_no)
  )

  if (nrow(version_row) == 0) {
    res$status <- 404
    return(list(error = "Version not found"))
  }

  spec <- wf_object_specs[[object_type]]
  updated_by <- trimws(as.character(parsed$updated_by %||% ""))

  DBI::dbExecute(
    con,
    sprintf(
      "
      UPDATE %s
      SET title = ?,
          content_json = ?,
          updated_by = ?,
          updated_at = CURRENT_TIMESTAMP,
          published_version = ?
      WHERE workspace = ?
        AND project = ?
        AND env = ?
        AND %s = ?
      ",
      spec$table,
      spec$id_col
    ),
    params = list(
      as.character(version_row$title[[1]] %||% ""),
      as.character(version_row$content_json[[1]]),
      updated_by,
      version_no,
      scope$workspace,
      scope$project,
      scope$env,
      id
    )
  )

  tags <- wf_json_decode(version_row$tags_json[[1]])
  if (is.null(tags)) {
    tags <- character()
  }

  DBI::dbExecute(
    con,
    "
    DELETE FROM tags
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND object_type = ?
      AND object_id = ?
    ",
    params = list(scope$workspace, scope$project, scope$env, object_type, id)
  )

  for (tg in unique(as.character(unlist(tags)))) {
    if (!nzchar(tg)) {
      next
    }
    DBI::dbExecute(
      con,
      "
      INSERT INTO tags (workspace, project, env, object_type, object_id, tag, created_at)
      VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
      ",
      params = list(scope$workspace, scope$project, scope$env, object_type, id, tg)
    )
  }

  if (identical(object_type, "automation")) {
    deps <- wf_json_decode(version_row$dependencies_json[[1]])

    DBI::dbExecute(
      con,
      "
      DELETE FROM dependencies
      WHERE workspace = ?
        AND project = ?
        AND env = ?
        AND source_type = 'automation'
        AND source_id = ?
      ",
      params = list(scope$workspace, scope$project, scope$env, id)
    )

    if (is.data.frame(deps) && nrow(deps) > 0) {
      for (i in seq_len(nrow(deps))) {
        DBI::dbExecute(
          con,
          "
          INSERT INTO dependencies (
            workspace, project, env, source_type, source_id, target_type, target_id, required, created_at
          )
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
          ",
          params = list(
            scope$workspace,
            scope$project,
            scope$env,
            "automation",
            id,
            as.character(deps$target_type[[i]]),
            as.character(deps$target_id[[i]]),
            isTRUE(deps$required[[i]])
          )
        )
      }
    }
  }

  current <- wf_find_object(object_type, id, scope)
  list(status = "rolled_back", object = wf_object_to_response(object_type, current, scope = scope))
}

wf_list_tags <- function(scope, object_type = NULL, object_id = NULL) {
  where <- c("workspace = ?", "project = ?", "env = ?")
  params <- list(scope$workspace, scope$project, scope$env)

  if (!is.null(object_type)) {
    where <- c(where, "object_type = ?")
    params <- c(params, list(object_type))
  }

  if (!is.null(object_id)) {
    where <- c(where, "object_id = ?")
    params <- c(params, list(object_id))
  }

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT object_type, object_id, tag, created_at
      FROM tags
      WHERE %s
      ORDER BY object_type, object_id, tag
      ",
      paste(where, collapse = " AND ")
    ),
    params = params
  )
}

wf_list_dependencies <- function(scope, source_type = NULL, source_id = NULL) {
  where <- c("workspace = ?", "project = ?", "env = ?")
  params <- list(scope$workspace, scope$project, scope$env)

  if (!is.null(source_type)) {
    where <- c(where, "source_type = ?")
    params <- c(params, list(source_type))
  }

  if (!is.null(source_id)) {
    where <- c(where, "source_id = ?")
    params <- c(params, list(source_id))
  }

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT source_type, source_id, target_type, target_id, required, created_at
      FROM dependencies
      WHERE %s
      ORDER BY source_type, source_id, target_type, target_id
      ",
      paste(where, collapse = " AND ")
    ),
    params = params
  )
}

wf_catalog_search <- function(scope, q = NULL, type = NULL, tag = NULL, sort_by = "updated_at", order = "desc", limit = 100, offset = 0) {
  sort_by <- wf_sort_field(sort_by, allowed = c("object_type", "object_id", "title", "updated_at", "published_version"), default = "updated_at")
  order <- wf_sort_order(order, default = "desc")
  limit <- wf_clamp_int(limit, default = 100L, min_value = 1L, max_value = 1000L)
  offset <- wf_clamp_int(offset, default = 0L, min_value = 0L, max_value = 100000L)

  q <- trimws(as.character(q %||% ""))
  tag <- trimws(as.character(tag %||% ""))
  has_q <- nzchar(q)
  has_tag <- nzchar(tag)
  object_type <- wf_object_type(type)

  where <- character()
  params <- list()

  if (!is.null(object_type)) {
    where <- c(where, "o.object_type = ?")
    params <- c(params, list(object_type))
  }
  if (has_q) {
    where <- c(where, "(LOWER(o.object_id) LIKE LOWER(?) OR LOWER(COALESCE(o.title, '')) LIKE LOWER(?))")
    params <- c(params, list(paste0("%", q, "%"), paste0("%", q, "%")))
  }
  if (has_tag) {
    where <- c(
      where,
      "EXISTS (
        SELECT 1
        FROM tags t
        WHERE t.workspace = o.workspace
          AND t.project = o.project
          AND t.env = o.env
          AND t.object_type = o.object_type
          AND t.object_id = o.object_id
          AND t.tag = ?
      )"
    )
    params <- c(params, list(tag))
  }

  where_sql <- if (length(where) == 0) "" else paste0("WHERE ", paste(where, collapse = " AND "))

  base_sql <- "
    WITH objects AS (
      SELECT workspace, project, env, 'context' AS object_type, context_id AS object_id, title, updated_at, published_version
      FROM contexts
      WHERE workspace = ? AND project = ? AND env = ?
      UNION ALL
      SELECT workspace, project, env, 'skill' AS object_type, skill_id AS object_id, title, updated_at, published_version
      FROM skills
      WHERE workspace = ? AND project = ? AND env = ?
      UNION ALL
      SELECT workspace, project, env, 'automation' AS object_type, automation_id AS object_id, title, updated_at, published_version
      FROM automations
      WHERE workspace = ? AND project = ? AND env = ?
    )
  "

  scope_params <- list(
    scope$workspace,
    scope$project,
    scope$env,
    scope$workspace,
    scope$project,
    scope$env,
    scope$workspace,
    scope$project,
    scope$env
  )

  total <- DBI::dbGetQuery(
    con,
    paste0(base_sql, " SELECT COUNT(*) AS n FROM objects o ", where_sql),
    params = c(scope_params, params)
  )

  rows <- DBI::dbGetQuery(
    con,
    paste0(
      base_sql,
      "
      SELECT o.object_type, o.object_id, o.title, o.updated_at, o.published_version
      FROM objects o
      ",
      where_sql,
      sprintf(
        "
        ORDER BY o.%s %s, o.object_type ASC, o.object_id ASC
        LIMIT %d
        OFFSET %d
        ",
        sort_by,
        order,
        limit,
        offset
      )
    ),
    params = c(scope_params, params)
  )

  items <- lapply(
    seq_len(nrow(rows)),
    function(i) {
      row <- rows[i, , drop = FALSE]
      obj_type <- as.character(row$object_type[[1]])
      obj_id <- as.character(row$object_id[[1]])
      list(
        object_type = obj_type,
        object_id = obj_id,
        title = as.character(row$title[[1]] %||% ""),
        updated_at = as.character(row$updated_at[[1]]),
        published_version = as.integer(row$published_version[[1]] %||% 0L),
        tags = wf_get_tags(obj_type, obj_id, scope)
      )
    }
  )

  list(
    items = items,
    total = as.integer(total$n[[1]]),
    limit = limit,
    offset = offset
  )
}

wf_catalog_tree <- function(scope, group_by = "type") {
  mode <- tolower(trimws(as.character(group_by %||% "type")))
  if (!(mode %in% c("type", "tag"))) {
    mode <- "type"
  }

  all_items <- wf_catalog_search(
    scope = scope,
    q = NULL,
    type = NULL,
    tag = NULL,
    sort_by = "updated_at",
    order = "desc",
    limit = 100000L,
    offset = 0L
  )$items

  if (identical(mode, "type")) {
    contexts <- all_items[vapply(all_items, function(x) identical(x$object_type, "context"), logical(1))]
    skills <- all_items[vapply(all_items, function(x) identical(x$object_type, "skill"), logical(1))]
    automations <- all_items[vapply(all_items, function(x) identical(x$object_type, "automation"), logical(1))]

    return(
      list(
        group_by = "type",
        groups = list(
          contexts = contexts,
          skills = skills,
          automations = automations
        )
      )
    )
  }

  tag_rows <- wf_list_tags(scope = scope)
  groups <- list()
  if (nrow(tag_rows) > 0) {
    for (i in seq_len(nrow(tag_rows))) {
      tg <- as.character(tag_rows$tag[[i]])
      if (is.null(groups[[tg]])) {
        groups[[tg]] <- list()
      }
      groups[[tg]][[length(groups[[tg]]) + 1L]] <- list(
        object_type = as.character(tag_rows$object_type[[i]]),
        object_id = as.character(tag_rows$object_id[[i]])
      )
    }
  }

  list(group_by = "tag", groups = groups)
}

wf_catalog_resolve <- function(res, req) {
  parsed <- wf_json_parse(req, res)
  if (!is.list(parsed) || !is.null(parsed$error)) {
    return(parsed)
  }

  refs <- parsed$refs
  if (is.null(refs) || !is.list(refs) || length(refs) == 0) {
    res$status <- 400
    return(list(error = "Field 'refs' must be a non-empty list"))
  }

  scope <- wf_scope(parsed$workspace %||% "personal", parsed$project %||% "default", parsed$env %||% "dev")
  include_dependencies <- isTRUE(parsed$include_dependencies %||% TRUE)

  resolved <- list()
  missing <- list()

  add_missing <- function(obj_type, obj_id) {
    missing[[length(missing) + 1L]] <<- list(object_type = obj_type, object_id = obj_id)
  }

  for (ref in refs) {
    obj_type <- wf_object_type(ref$object_type %||% "")
    obj_id <- wf_id(ref$object_id %||% "")
    if (is.null(obj_type) || is.null(obj_id)) {
      add_missing(ref$object_type, ref$object_id)
      next
    }

    row <- wf_find_object(obj_type, obj_id, scope)
    if (is.null(row)) {
      add_missing(obj_type, obj_id)
      next
    }

    resolved[[length(resolved) + 1L]] <- wf_object_to_response(obj_type, row, scope = scope)

    if (include_dependencies && identical(obj_type, "automation")) {
      deps <- wf_get_dependencies("automation", obj_id, scope)
      if (nrow(deps) > 0) {
        for (i in seq_len(nrow(deps))) {
          tgt_type <- wf_object_type(as.character(deps$target_type[[i]]))
          tgt_id <- wf_id(as.character(deps$target_id[[i]]))
          if (is.null(tgt_type) || is.null(tgt_id)) {
            next
          }
          tgt_row <- wf_find_object(tgt_type, tgt_id, scope)
          if (is.null(tgt_row)) {
            add_missing(tgt_type, tgt_id)
          } else {
            resolved[[length(resolved) + 1L]] <- wf_object_to_response(tgt_type, tgt_row, scope = scope)
          }
        }
      }
    }
  }

  dedupe <- function(items) {
    out <- list()
    seen <- character()
    for (it in items) {
      key <- paste0(as.character(it$object_type %||% ""), ":", as.character(it$object_id %||% ""))
      if (key %in% seen) {
        next
      }
      seen <- c(seen, key)
      out[[length(out) + 1L]] <- it
    }
    out
  }

  list(
    resolved = dedupe(resolved),
    missing = dedupe(missing)
  )
}

#* List contexts.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/contexts
function(res, workspace = "personal", project = "default", env = "dev", tag = NULL, q = NULL, sort_by = "updated_at", order = "desc", limit = 100, offset = 0) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_list_objects("context", scope = wf_scope(workspace, project, env), tag = tag, q = q, sort_by = sort_by, order = order, limit = limit, offset = offset)
}

#* Get one context by id.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/contexts/<context_id>
function(res, context_id, workspace = "personal", project = "default", env = "dev", version = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_get_object(res, "context", context_id, wf_scope(workspace, project, env), version = version)
}

#* Upsert context draft state.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @put /v1/contexts/<context_id>
function(req, res, context_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_upsert_object(res, req, "context", context_id, wf_scope(workspace, project, env))
}

#* Publish context to a new immutable version.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/contexts/<context_id>/publish
function(req, res, context_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_publish_object(res, req, "context", context_id, wf_scope(workspace, project, env))
}

#* List context versions.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/contexts/<context_id>/versions
function(res, context_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_list_versions("context", context_id, wf_scope(workspace, project, env))
}

#* Roll back context draft state to a prior version.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/contexts/<context_id>/rollback
function(req, res, context_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_rollback(res, req, "context", context_id, wf_scope(workspace, project, env))
}

#* List skills.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/skills
function(res, workspace = "personal", project = "default", env = "dev", tag = NULL, q = NULL, sort_by = "updated_at", order = "desc", limit = 100, offset = 0) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_list_objects("skill", scope = wf_scope(workspace, project, env), tag = tag, q = q, sort_by = sort_by, order = order, limit = limit, offset = offset)
}

#* Get one skill by id.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/skills/<skill_id>
function(res, skill_id, workspace = "personal", project = "default", env = "dev", version = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_get_object(res, "skill", skill_id, wf_scope(workspace, project, env), version = version)
}

#* Upsert skill draft state.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @put /v1/skills/<skill_id>
function(req, res, skill_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_upsert_object(res, req, "skill", skill_id, wf_scope(workspace, project, env))
}

#* Publish skill to a new immutable version.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/skills/<skill_id>/publish
function(req, res, skill_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_publish_object(res, req, "skill", skill_id, wf_scope(workspace, project, env))
}

#* List skill versions.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/skills/<skill_id>/versions
function(res, skill_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_list_versions("skill", skill_id, wf_scope(workspace, project, env))
}

#* Roll back skill draft state to a prior version.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/skills/<skill_id>/rollback
function(req, res, skill_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_rollback(res, req, "skill", skill_id, wf_scope(workspace, project, env))
}

#* List automations.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/automations
function(res, workspace = "personal", project = "default", env = "dev", tag = NULL, q = NULL, sort_by = "updated_at", order = "desc", limit = 100, offset = 0) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_list_objects("automation", scope = wf_scope(workspace, project, env), tag = tag, q = q, sort_by = sort_by, order = order, limit = limit, offset = offset)
}

#* Get one automation by id.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/automations/<automation_id>
function(res, automation_id, workspace = "personal", project = "default", env = "dev", version = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_get_object(res, "automation", automation_id, wf_scope(workspace, project, env), version = version)
}

#* Upsert automation draft state.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @put /v1/automations/<automation_id>
function(req, res, automation_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_upsert_object(res, req, "automation", automation_id, wf_scope(workspace, project, env))
}

#* Publish automation to a new immutable version.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/automations/<automation_id>/publish
function(req, res, automation_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_publish_object(res, req, "automation", automation_id, wf_scope(workspace, project, env))
}

#* List automation versions.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/automations/<automation_id>/versions
function(res, automation_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_list_versions("automation", automation_id, wf_scope(workspace, project, env))
}

#* Roll back automation draft state to a prior version.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/automations/<automation_id>/rollback
function(req, res, automation_id, workspace = "personal", project = "default", env = "dev") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_rollback(res, req, "automation", automation_id, wf_scope(workspace, project, env))
}

#* Replace tags for an object.
#* Body fields: `object_type`, `object_id`, `tags` (array).
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @put /v1/tags
function(req, res) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  parsed <- wf_json_parse(req, res)
  if (!is.list(parsed) || !is.null(parsed$error)) {
    return(parsed)
  }

  object_type <- wf_object_type(parsed$object_type)
  object_id <- wf_id(parsed$object_id)
  scope <- wf_scope(parsed$workspace %||% "personal", parsed$project %||% "default", parsed$env %||% "dev")

  if (is.null(object_type) || is.null(object_id)) {
    res$status <- 400
    return(list(error = "Fields 'object_type' and 'object_id' are required"))
  }

  if (is.null(wf_find_object(object_type, object_id, scope))) {
    res$status <- 404
    return(list(error = "Object not found"))
  }

  tags <- parsed$tags %||% character()
  tags <- unique(trimws(as.character(unlist(tags))))
  tags <- tags[nzchar(tags)]

  DBI::dbExecute(
    con,
    "
    DELETE FROM tags
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND object_type = ?
      AND object_id = ?
    ",
    params = list(scope$workspace, scope$project, scope$env, object_type, object_id)
  )

  for (tag in tags) {
    DBI::dbExecute(
      con,
      "
      INSERT INTO tags (workspace, project, env, object_type, object_id, tag, created_at)
      VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
      ",
      params = list(scope$workspace, scope$project, scope$env, object_type, object_id, tag)
    )
  }

  list(status = "saved", object_type = object_type, object_id = object_id, tags = tags)
}

#* List tags.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/tags
function(res, workspace = "personal", project = "default", env = "dev", object_type = NULL, object_id = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  obj_type <- NULL
  if (!is.null(object_type) && nzchar(trimws(as.character(object_type)))) {
    obj_type <- wf_object_type(object_type)
    if (is.null(obj_type)) {
      res$status <- 400
      return(list(error = "Invalid object_type"))
    }
  }

  obj_id <- NULL
  if (!is.null(object_id) && nzchar(trimws(as.character(object_id)))) {
    obj_id <- wf_id(object_id)
  }

  wf_list_tags(scope = wf_scope(workspace, project, env), object_type = obj_type, object_id = obj_id)
}

#* Delete tags for an object, optionally a specific tag.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @delete /v1/tags
function(res, workspace = "personal", project = "default", env = "dev", object_type = NULL, object_id = NULL, tag = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  obj_type <- wf_object_type(object_type)
  obj_id <- wf_id(object_id)
  tg <- wf_id(tag)

  if (is.null(obj_type) || is.null(obj_id)) {
    res$status <- 400
    return(list(error = "Query params 'object_type' and 'object_id' are required"))
  }

  where <- c("workspace = ?", "project = ?", "env = ?", "object_type = ?", "object_id = ?")
  params <- list(workspace, project, env, obj_type, obj_id)
  if (!is.null(tg)) {
    where <- c(where, "tag = ?")
    params <- c(params, list(tg))
  }

  DBI::dbExecute(
    con,
    sprintf("DELETE FROM tags WHERE %s", paste(where, collapse = " AND ")),
    params = params
  )

  list(status = "deleted", object_type = obj_type, object_id = obj_id, tag = tg)
}

#* Upsert one dependency edge.
#* Body fields: `source_type`, `source_id`, `target_type`, `target_id`.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @put /v1/dependencies
function(req, res) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  parsed <- wf_json_parse(req, res)
  if (!is.list(parsed) || !is.null(parsed$error)) {
    return(parsed)
  }

  scope <- wf_scope(parsed$workspace %||% "personal", parsed$project %||% "default", parsed$env %||% "dev")
  source_type <- wf_object_type(parsed$source_type)
  source_id <- wf_id(parsed$source_id)
  target_type <- wf_object_type(parsed$target_type)
  target_id <- wf_id(parsed$target_id)

  if (is.null(source_type) || is.null(source_id) || is.null(target_type) || is.null(target_id)) {
    res$status <- 400
    return(list(error = "Fields source_type/source_id/target_type/target_id are required"))
  }

  if (is.null(wf_find_object(source_type, source_id, scope))) {
    res$status <- 404
    return(list(error = "Source object not found"))
  }
  if (is.null(wf_find_object(target_type, target_id, scope))) {
    res$status <- 404
    return(list(error = "Target object not found"))
  }

  required <- isTRUE(parsed$required %||% TRUE)

  DBI::dbExecute(
    con,
    "
    INSERT INTO dependencies (
      workspace, project, env, source_type, source_id, target_type, target_id, required, created_at
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
    ON CONFLICT (workspace, project, env, source_type, source_id, target_type, target_id)
    DO UPDATE SET required = EXCLUDED.required
    ",
    params = list(scope$workspace, scope$project, scope$env, source_type, source_id, target_type, target_id, required)
  )

  list(status = "saved")
}

#* List dependency edges.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/dependencies
function(res, workspace = "personal", project = "default", env = "dev", source_type = NULL, source_id = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  src_type <- NULL
  if (!is.null(source_type) && nzchar(trimws(as.character(source_type)))) {
    src_type <- wf_object_type(source_type)
    if (is.null(src_type)) {
      res$status <- 400
      return(list(error = "Invalid source_type"))
    }
  }

  src_id <- NULL
  if (!is.null(source_id) && nzchar(trimws(as.character(source_id)))) {
    src_id <- wf_id(source_id)
  }

  wf_list_dependencies(scope = wf_scope(workspace, project, env), source_type = src_type, source_id = src_id)
}

#* Delete one dependency edge.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @delete /v1/dependencies
function(res, workspace = "personal", project = "default", env = "dev", source_type = NULL, source_id = NULL, target_type = NULL, target_id = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  src_type <- wf_object_type(source_type)
  src_id <- wf_id(source_id)
  tgt_type <- wf_object_type(target_type)
  tgt_id <- wf_id(target_id)

  if (is.null(src_type) || is.null(src_id) || is.null(tgt_type) || is.null(tgt_id)) {
    res$status <- 400
    return(list(error = "Query params source_type/source_id/target_type/target_id are required"))
  }

  DBI::dbExecute(
    con,
    "
    DELETE FROM dependencies
    WHERE workspace = ?
      AND project = ?
      AND env = ?
      AND source_type = ?
      AND source_id = ?
      AND target_type = ?
      AND target_id = ?
    ",
    params = list(workspace, project, env, src_type, src_id, tgt_type, tgt_id)
  )

  list(status = "deleted")
}

#* Search contexts, skills, and automations with unified filters.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/catalog/search
function(res, workspace = "personal", project = "default", env = "dev", q = NULL, type = NULL, tag = NULL, sort_by = "updated_at", order = "desc", limit = 100, offset = 0) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_catalog_search(
    scope = wf_scope(workspace, project, env),
    q = q,
    type = type,
    tag = tag,
    sort_by = sort_by,
    order = order,
    limit = limit,
    offset = offset
  )
}

#* Return catalog grouped by type or tag.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/catalog/tree
function(res, workspace = "personal", project = "default", env = "dev", group_by = "type") {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_catalog_tree(scope = wf_scope(workspace, project, env), group_by = group_by)
}

#* Resolve explicit refs into full current objects.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/catalog/resolve
function(req, res) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_catalog_resolve(res, req)
}

wf_to_character_vector <- function(x) {
  if (is.null(x)) {
    return(character())
  }
  as.character(unlist(x))
}

wf_lint_skill_object <- function(obj) {
  issues <- character()
  warnings <- character()

  title <- trimws(as.character(obj$title %||% ""))
  if (!nzchar(title)) {
    warnings <- c(warnings, "Skill title is empty.")
  }

  content <- obj$content
  if (is.null(content) || !(is.list(content) || is.atomic(content))) {
    issues <- c(issues, "Skill content is missing or invalid.")
  } else if (!is.list(content)) {
    warnings <- c(warnings, "Skill content is not an object; prefer object-shaped JSON.")
  }

  if (is.list(content) && !is.null(content$prompt)) {
    prompt <- trimws(as.character(content$prompt %||% ""))
    if (!nzchar(prompt)) {
      warnings <- c(warnings, "Skill prompt is present but empty.")
    }
  }

  list(
    valid = length(issues) == 0L,
    issues = issues,
    warnings = warnings
  )
}

wf_validate_automation_object <- function(obj, scope) {
  issues <- character()
  warnings <- character()

  trigger_type <- trimws(as.character(obj$trigger_type %||% ""))
  if (!nzchar(trigger_type)) {
    warnings <- c(warnings, "Automation trigger_type is empty.")
  }

  content <- obj$content
  if (is.null(content) || !(is.list(content) || is.atomic(content))) {
    issues <- c(issues, "Automation content is missing or invalid.")
  } else if (!is.list(content)) {
    warnings <- c(warnings, "Automation content is not an object; prefer object-shaped JSON.")
  }

  deps <- obj$dependencies
  if (!is.data.frame(deps)) {
    deps <- data.frame(
      source_type = character(),
      source_id = character(),
      target_type = character(),
      target_id = character(),
      required = logical(),
      stringsAsFactors = FALSE
    )
  }

  missing_dependencies <- list()

  if (nrow(deps) > 0) {
    for (i in seq_len(nrow(deps))) {
      target_type <- wf_object_type(as.character(deps$target_type[[i]] %||% ""))
      target_id <- wf_id(as.character(deps$target_id[[i]] %||% ""))
      required <- isTRUE(deps$required[[i]] %||% TRUE)

      if (is.null(target_type) || is.null(target_id)) {
        missing_dependencies[[length(missing_dependencies) + 1L]] <- list(
          target_type = deps$target_type[[i]],
          target_id = deps$target_id[[i]],
          required = required,
          reason = "invalid_target_reference"
        )
        issues <- c(issues, "Automation contains dependency with invalid target reference.")
        next
      }

      target_row <- wf_find_object(target_type, target_id, scope)
      if (is.null(target_row)) {
        missing_dependencies[[length(missing_dependencies) + 1L]] <- list(
          target_type = target_type,
          target_id = target_id,
          required = required,
          reason = "target_not_found"
        )
        if (required) {
          issues <- c(issues, paste0("Missing required dependency: ", target_type, ":", target_id))
        } else {
          warnings <- c(warnings, paste0("Missing optional dependency: ", target_type, ":", target_id))
        }
      }
    }
  }

  list(
    valid = length(issues) == 0L,
    issues = unique(issues),
    warnings = unique(warnings),
    dependency_count = nrow(deps),
    missing_dependencies = missing_dependencies
  )
}

wf_ref_integrity <- function(scope, limit = 500L) {
  limit <- wf_clamp_int(limit, default = 500L, min_value = 1L, max_value = 5000L)

  dependency_rows <- wf_list_dependencies(scope = scope)
  tag_rows <- wf_list_tags(scope = scope)

  broken_dependencies <- list()
  broken_tags <- list()

  if (nrow(dependency_rows) > 0) {
    for (i in seq_len(nrow(dependency_rows))) {
      src_type <- wf_object_type(as.character(dependency_rows$source_type[[i]] %||% ""))
      src_id <- wf_id(as.character(dependency_rows$source_id[[i]] %||% ""))
      tgt_type <- wf_object_type(as.character(dependency_rows$target_type[[i]] %||% ""))
      tgt_id <- wf_id(as.character(dependency_rows$target_id[[i]] %||% ""))

      source_exists <- !is.null(src_type) && !is.null(src_id) && !is.null(wf_find_object(src_type, src_id, scope))
      target_exists <- !is.null(tgt_type) && !is.null(tgt_id) && !is.null(wf_find_object(tgt_type, tgt_id, scope))

      if (!source_exists || !target_exists) {
        broken_dependencies[[length(broken_dependencies) + 1L]] <- list(
          source_type = dependency_rows$source_type[[i]],
          source_id = dependency_rows$source_id[[i]],
          target_type = dependency_rows$target_type[[i]],
          target_id = dependency_rows$target_id[[i]],
          source_exists = source_exists,
          target_exists = target_exists
        )
      }
    }
  }

  if (nrow(tag_rows) > 0) {
    for (i in seq_len(nrow(tag_rows))) {
      obj_type <- wf_object_type(as.character(tag_rows$object_type[[i]] %||% ""))
      obj_id <- wf_id(as.character(tag_rows$object_id[[i]] %||% ""))
      exists <- !is.null(obj_type) && !is.null(obj_id) && !is.null(wf_find_object(obj_type, obj_id, scope))
      if (!exists) {
        broken_tags[[length(broken_tags) + 1L]] <- list(
          object_type = tag_rows$object_type[[i]],
          object_id = tag_rows$object_id[[i]],
          tag = tag_rows$tag[[i]]
        )
      }
    }
  }

  list(
    valid = length(broken_dependencies) == 0L && length(broken_tags) == 0L,
    workspace = scope$workspace,
    project = scope$project,
    env = scope$env,
    totals = list(
      dependencies = nrow(dependency_rows),
      tags = nrow(tag_rows)
    ),
    broken_counts = list(
      dependencies = length(broken_dependencies),
      tags = length(broken_tags)
    ),
    broken_dependencies = utils::head(broken_dependencies, n = limit),
    broken_tags = utils::head(broken_tags, n = limit)
  )
}

#* Lint a skill draft/version for basic structural issues.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/skills/<skill_id>/lint
function(res, skill_id, workspace = "personal", project = "default", env = "dev", version = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  scope <- wf_scope(workspace, project, env)
  obj <- wf_get_object(res, "skill", skill_id, scope, version = version)
  if (!is.null(obj$error)) {
    return(obj)
  }

  report <- wf_lint_skill_object(obj)
  list(
    object_type = "skill",
    object_id = skill_id,
    workspace = scope$workspace,
    project = scope$project,
    env = scope$env,
    version = obj$version %||% NULL,
    valid = report$valid,
    issues = report$issues,
    warnings = report$warnings
  )
}

#* Validate automation draft/version for structural and dependency integrity.
#* @tag Workflows
#* @serializer json list(auto_unbox = TRUE)
#* @post /v1/automations/<automation_id>/validate
function(res, automation_id, workspace = "personal", project = "default", env = "dev", version = NULL) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  scope <- wf_scope(workspace, project, env)
  obj <- wf_get_object(res, "automation", automation_id, scope, version = version)
  if (!is.null(obj$error)) {
    return(obj)
  }

  report <- wf_validate_automation_object(obj, scope)
  list(
    object_type = "automation",
    object_id = automation_id,
    workspace = scope$workspace,
    project = scope$project,
    env = scope$env,
    version = obj$version %||% NULL,
    valid = report$valid,
    issues = report$issues,
    warnings = report$warnings,
    dependency_count = report$dependency_count,
    missing_dependencies = report$missing_dependencies
  )
}

#* Validate cross-object reference integrity for tags and dependencies in scope.
#* @tag Workflows
#* @param limit:int Maximum broken refs returned per category (1..5000).
#* @serializer json list(auto_unbox = TRUE)
#* @get /v1/validate/ref-integrity
function(res, workspace = "personal", project = "default", env = "dev", limit = 500) {
  missing <- wf_ensure_tables(res)
  if (!is.null(missing)) {
    return(missing)
  }

  wf_ref_integrity(wf_scope(workspace, project, env), limit = limit)
}

# ---- notes.R ----
#* List notes ordered by newest first.
#* Requires bearer authentication.
#* @tag Notes
#* @param limit:int Maximum records to return (clamped to 1..1000).
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Notes returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @get /notes
function(limit = 100) {
  limit <- as.integer(limit)
  if (is.na(limit) || limit < 1) {
    limit <- 100
  }
  if (limit > 1000) {
    limit <- 1000
  }

  DBI::dbGetQuery(
    con,
    sprintf(
      "
      SELECT id, text, created_at
      FROM notes
      ORDER BY created_at DESC
      LIMIT %d
      ",
      limit
    )
  )
}

#* Create a note from a JSON body.
#* Body shape: `{ \"text\": \"...\" }`.
#* Requires bearer authentication.
#* @tag Notes
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Note created successfully.
#* @response 400 Invalid JSON body or missing `text` field.
#* @response 401 Missing or invalid bearer token.
#* @post /notes
function(req, res) {
  body <- tryCatch(
    jsonlite::fromJSON(req$postBody %||% ""),
    error = function(e) NULL
  )

  if (is.null(body)) {
    res$status <- 400
    return(list(error = "Invalid JSON body"))
  }

  if (is.null(body$text) || length(body$text) != 1 || !is.character(body$text)) {
    res$status <- 400
    return(list(error = "Field 'text' is required"))
  }

  note_text <- trimws(body$text)
  if (!nzchar(note_text)) {
    res$status <- 400
    return(list(error = "Field 'text' is required"))
  }

  id <- uuid::UUIDgenerate()

  DBI::dbExecute(
    con,
    "INSERT INTO notes (id, text, created_at) VALUES (?, ?, CURRENT_TIMESTAMP)",
    params = list(id, note_text)
  )

  list(id = id, text = note_text, status = "created")
}

# ---- tables.R ----
#* List curated warehouse table metadata.
#* Requires bearer authentication.
#* @tag Warehouse
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Table metadata returned successfully.
#* @response 401 Missing or invalid bearer token.
#* @get /tables
function() {
  DBI::dbGetQuery(
    con,
    "
    SELECT
      schema_name,
      table_name,
      object_name,
      source_path,
      relative_path,
      row_count,
      last_refresh
    FROM warehouse.tables
    ORDER BY schema_name, table_name
    "
  )
}

# ---- admin.R ----
#* Force a curated view refresh from Parquet mappings.
#* Requires bearer authentication.
#* @tag Warehouse
#* @serializer json list(auto_unbox = TRUE)
#* @response 200 Curated view refresh completed.
#* @response 401 Missing or invalid bearer token.
#* @post /admin/refresh-curated
function() {
  refresh_curated_views(force = TRUE)
}
